### ISSUE TITLE
Should support uppercase header names

### ISSUE THREAD

**Issue by robtucker** [radiosilence/redux-rx-http#1]
The use of fetch API is preventing me from calling a 3rd party endpoint who require a case sensitive 'Auth-Token' header - see related issue here: https://github.com/whatwg/fetch/issues/304. May potentially be a fix involving accessing raw headers? Or alternatively move to XmlHttpRequest

**Comment by radiosilence** [comment]
Will be resolved if/when fetch or chrome does this. Not moving back to XMLHttpRequest
