### ISSUE TITLE
No body is included in request on rxHttpPost

### ISSUE THREAD

**Issue by robtucker** [radiosilence/redux-rx-http#2]
The body is simply missing on the request - using latest chrome with version 0.7.7 - think we should implement some unit tests to confirm headers and body are being added to requests as expected

**Comment by radiosilence** [comment]
This was (I think) due to passing a JavaScript object as the body, whereas it needs to be stringified. In 0.8, I've added a helper flag `json` in the request config which means it'll stringify, which also can be supplied in the epic config.

Like this
```typescript
rxHttpPost('/', POTATO, { some: 'data' }, {
  request: { json: true },
})
```

Or like this

```typescript
const rxHttpEpic = createRxHttpEpic(() => ({
  ...
  json: true,
}))
```
